# Generated by Django 2.1.5 on 2019-02-13 10:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('marque', models.CharField(max_length=42)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('description', models.TextField(null=True)),
                ('nb_visite', models.IntegerField(null=True)),
                ('date_ajout', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'ajout")),
                ('publie_le', models.DateTimeField(null=True, verbose_name='Publié Le')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Produit publié ?')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Image')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Produit')),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='images',
            field=models.ManyToManyField(related_name='_produit_images_+', through='market.ProduitImage', to='market.Image'),
        ),
        migrations.AddField(
            model_name='produit',
            name='logo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='market.Image', verbose_name='Image Principale'),
        ),
    ]
