# Generated by Django 2.1.5 on 2019-03-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_commande_est_suppr'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='taxe_sur_livraison',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
