# Generated by Django 2.1.5 on 2019-03-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_produit_taxe_sur_livraison'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='taxe_sur_livraison',
        ),
        migrations.AddField(
            model_name='commande',
            name='pret_a_payer',
            field=models.BooleanField(default=True, verbose_name='Commande prete à payer ?'),
        ),
        migrations.AddField(
            model_name='commande',
            name='taxe_sur_livraison',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
